export const COMMENT_ACTION_TYPES = {
    COMMENT_ACTION_CREATE_START : "auth/COMMENT_ACTION_CREATE_START",
    COMMENT_ACTION_CREATE_SUCCESS : "auth/COMMENT_ACTION_CREATE_SUCCESS",
    COMMENT_ACTION_CREATE_FAILED : "auth/COMMENT_ACTION_CREATE_FAILED",
    COMMENT_ACTION_DELETE_START:  "auth/COMMENT_ACTION_DELETE_START",
    COMMENT_ACTION_DELETE_SUCCESS:  "auth/COMMENT_ACTION_DELETE_SUCCESS",
    COMMENT_ACTION_DELETE_FAILED : "auth/COMMENT_ACTION_DELETE_FAILED",    
    COMMENT_ACTION_FETCH_START:  "auth/COMMENT_ACTION_FETCH_START",
    COMMENT_ACTION_FETCH_SUCCESS:  "auth/COMMENT_ACTION_FETCH_SUCCESS",
    COMMENT_ACTION_FETCH_FAILED : "auth/COMMENT_ACTION_FETCH_FAILED",
   
}