export const AUTH_ACTION_TYPES = {
    AUTH_ACTION_START : "auth/AUTH_ACTION_START",
    AUTH_ACTION_SETUSER :  "auth/AUTH_ACTION_SETUSER",
    AUTH_ACTION_UNSETUSER : "auth/AUTH_ACTION_UNSETUSER",
    AUTH_ACTION_FAILED : "auth/AUTH_ACTION_FAILED",
}