export const DS_ACTION_TYPES = {
    DS_ACTION_START : "auth/DS_ACTION_START",
    DS_ACTION_SETESPACEARRAY :  "auth/DS_ACTION_SETESPACEARRAY",
    DS_ACTION_FAILED : "auth/DS_ACTION_FAILED",
    DS_ACTION_SETCURRENTSPACE : "auth/DS_ACTION_SETCURRENTSPACE",
}