export const POSTS_ACTION_TYPES = {
    POSTS_ACTION_START : "posts/POSTS_ACTION_START",
    POSTS_ACTION_SUCCESS : "posts/POSTS_ACTION_SUCCESS",
    POSTS_ACTION_FAILED : "posts/POSTS_ACTION_FAILED",
}